### ISSUE TITLE
Culture-aware custom mapping

### ISSUE THREAD

**Issue by UkeHa** [ChrisHodges/ExcelToEnumerable#3]
When i try to add a number given in a german format (e.g. 299,99 with a , instead of a .), the conversion is ignored and returns 29999.00 instead. So i went ahead and added a custom mapping, but as far as i can see, this conversion is ignored. 

`.Property(y => y.MyGermanValue).UsesCustomMapping(cellValueObject => Convert.ToDouble(cellValueObject, new CultureInfo("de-de")))`

How can i add such culture info?

**Comment by ChrisHodges** [comment]
Hi Uke.

Thanks for raising this. You've uncovered a bug in the underlying [LightweightExcelReader package](https://github.com/ChrisHodges/LightweightExcelReader), which was parsing the XML using the current thread culture, rather than an invariant culture. In an .xlsx file decimals are stored using a period (.) regardless of the formatting of the cell, so a value displayed as `1,234` would be stored as `1.234`, but was being parsed by the reader as `1234.0` if the culture of the thread was `de-DE`.

I've fixed the issue [here](https://github.com/ChrisHodges/LightweightExcelReader/commit/b1120883972073178368849e586f20834f70d4a2#diff-7ff4d8f58f3fcd2c0630bc852363b9fd7cef706f444f5dcf07a4d309055f72ac) and updated **ExcelToEnumerable** to use the updated LightweightExcelReader package so upgrading to [version 0.3.7](https://www.nuget.org/packages/ExcelToEnumerable/0.3.7) should parse decimals correctly without having to use a custom mapping.

Let me know if this fixes your issue.

**Comment by UkeHa** [comment]
Hi Chris,

no, that doesn't work (see [here](https://dotnetfiddle.net/qc1a0y)) . 
The problem is that german culture uses comma to distinguish the fractions and dots are sometimes used as a separator for thousands. Even when using `double.TryParse(amount, NumberStyles.Any, CultureInfo.InvariantCulture, out result); ` to account for number styles this won't work. 
For the conversion to run properly you'd need to find out which culture was used in excel and use that culture as the global definition when parsing any double, because the trial and error method doesn't work properly.

**Comment by ChrisHodges** [comment]
Are you able to email me an example of a spreadsheet that is exhibiting this issue, and a .cs file containing the class that you are attempting to map to?

**Comment by UkeHa** [comment]
I sent you a new project to reproduce the problem as well as an excel file.

**Comment by ChrisHodges** [comment]
There was a variation of sheet format that I had overlooked on LightweightExcelReader. I've fixed this and upgraded the reader package version in ExcelToEnumerable. Can you try upgrading to [version 0.3.8](https://www.nuget.org/packages/ExcelToEnumerable/0.3.8) and let me know if that solves the problem? It's now working correctly on the project you sent me.

**Comment by UkeHa** [comment]
Version 0.3.8 fixes the problem.
